name: s2s_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - pytorch=2.0.1
  - torchtext=0.15.2
  - torchdata=0.6.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - spacy=3.7.2
  - pip
  - pip:
      - en-core-web-sm
      - de-core-news-sm
